apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-spring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: java=749698443047.dkr.ecr.us-east-1.amazonaws.com/challenge/java-spring
    argocd-image-updater.argoproj.io/java.update-strategy: latest
    argocd-image-updater.argoproj.io/java.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/java.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/java.helm.image-tag: image.tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asfcjr/dd-stack.git
    targetRevision: main
    path: helm/app
    helm:
      releaseName: java-spring
      valueFiles:
        - ../values/java.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
