apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-todoapi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: dotnet=749698443047.dkr.ecr.us-east-1.amazonaws.com/challenge/dotnet-todoapi
    argocd-image-updater.argoproj.io/dotnet.update-strategy: newest-build
    argocd-image-updater.argoproj.io/dotnet.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/dotnet.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/dotnet.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/image-updater-git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:../values/dotnet.yaml
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asfcjr/dd-stack.git
    targetRevision: main
    path: helm/app
    helm:
      releaseName: dotnet-todoapi
      valueFiles:
        - ../values/dotnet.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
