apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-flask
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: python=749698443047.dkr.ecr.us-east-1.amazonaws.com/challenge/python-flask
    argocd-image-updater.argoproj.io/python.update-strategy: newest-build
    argocd-image-updater.argoproj.io/python.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/python.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/python.helm.image-tag: image.tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asfcjr/dd-stack.git
    targetRevision: main
    path: helm/app
    helm:
      releaseName: python-flask
      valueFiles:
        - ../values/python.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
