apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: rabbitmq
    targetRevision: 14.7.0
    helm:
      releaseName: rabbitmq
      valuesObject:
        global:
          security:
            allowInsecureImages: true
        image:
          repository: bitnamilegacy/rabbitmq
        auth:
          username: user
          existingPasswordSecret: rabbitmq-credentials
          existingSecretPasswordKey: rabbitmq-password
        replicaCount: 3
        pdb:
          create: true
          minAvailable: 2
        clustering:
          forceBoot: true
        service:
          type: NodePort
        metrics:
          enabled: true
        podAnnotations:
          ad.datadoghq.com/rabbitmq.checks: |
            {"rabbitmq":{"instances":[{"prometheus_plugin":{"url":"http://%%host%%:15692"}}]}}
  destination:
    server: https://kubernetes.default.svc
    namespace: middleware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
