name: java-spring
image:
  repository: 749698443047.dkr.ecr.us-east-1.amazonaws.com/challenge/java-spring
  tag: a8bb03e
containerPort: 8080
service:
  type: NodePort
  port: 8083
datadog:
  env: challenge
  service: java-spring
  version: "1.0"
  lib: java
  libVersion: latest
resources:
  requests: {cpu: 250m, memory: 384Mi}
  limits: {memory: 768Mi}
