name: python-flask
image:
  repository: 749698443047.dkr.ecr.us-east-1.amazonaws.com/challenge/python-flask
  tag: 18783c3
containerPort: 5000
service:
  type: NodePort
  port: 8082
datadog:
  env: challenge
  service: python-flask
  version: "1.0"
  lib: python
  libVersion: latest
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {memory: 256Mi}
