datadog:
  site: datadoghq.com
  clusterName: challenge-cluster
  apiKeyExistingSecret: datadog-secret

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    portEnabled: true
    socketEnabled: true

  processAgent:
    enabled: true

  clusterChecks:
    enabled: true

  orchestratorExplorer:
    enabled: true

  tags:
    - "env:challenge"

clusterAgent:
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false

registry: public.ecr.aws/datadog
